// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfigRoot: () => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("get_config_root")),
	getConfigSnapshot: () => typedError<AppConfigSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("get_config_snapshot")),
	getResourceSettings: () => typedError<ResourceSettings, ConfigError>(__TAURI_INVOKE("get_resource_settings")),
	collectResourceMonitorSnapshot: (input: ResourceMonitorCollectInput) => typedError<ResourceMonitorSnapshot, ConfigError>(__TAURI_INVOKE("collect_resource_monitor_snapshot", { input })),
	getTerminalSettings: () => typedError<TerminalSettings, ConfigError>(__TAURI_INVOKE("get_terminal_settings")),
	getTerminalSettingsForTheme: (input: TerminalSettingsInput) => typedError<TerminalSettings, ConfigError>(__TAURI_INVOKE("get_terminal_settings_for_theme", { input })),
	createHostTerminalSession: (input: CreateHostTerminalSessionInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("create_host_terminal_session", { input })),
	existingTerminalSessionInfo: (input: ExistingTerminalSessionInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("existing_terminal_session_info", { input })),
	transferTerminalSessionsToWindow: (input: TerminalSessionOwnershipInput) => typedError<null, ConfigError>(__TAURI_INVOKE("transfer_terminal_sessions_to_window", { input })),
	detachTerminalSession: (input: TerminalDetachInput) => typedError<TerminalDetachedSessionInfo, ConfigError>(__TAURI_INVOKE("detach_terminal_session", { input })),
	listDetachedTerminalSessions: (input: DetachedTerminalSessionsInput) => typedError<TerminalDetachedSessionInfo[], ConfigError>(__TAURI_INVOKE("list_detached_terminal_sessions", { input })),
	attachDetachedTerminalSession: (input: AttachDetachedTerminalSessionInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("attach_detached_terminal_session", { input })),
	openDetachedTerminalSessionHistory: (input: OpenDetachedTerminalSessionHistoryInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("open_detached_terminal_session_history", { input })),
	deleteDetachedTerminalSession: (input: DeleteDetachedTerminalSessionInput) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_detached_terminal_session", { input })),
	exportTerminalSessionKey: (sessionId: string) => typedError<string, ConfigError>(__TAURI_INVOKE("export_terminal_session_key", { sessionId })),
	takeTerminalOutputBacklog: (input: TerminalOutputBacklogInput) => typedError<{
	session_id: string,
	sequence: string,
	backlog: boolean,
	data: string,
} | null, ConfigError>(__TAURI_INVOKE("take_terminal_output_backlog", { input })),
	writeTerminal: (input: TerminalInput) => typedError<null, ConfigError>(__TAURI_INVOKE("write_terminal", { input })),
	resizeTerminal: (input: TerminalSizeInput) => typedError<null, ConfigError>(__TAURI_INVOKE("resize_terminal", { input })),
	renameTerminalSession: (input: TerminalTitleInput) => typedError<null, ConfigError>(__TAURI_INVOKE("rename_terminal_session", { input })),
	updateTerminalTitle: (input: TerminalTitleInput) => typedError<null, ConfigError>(__TAURI_INVOKE("update_terminal_title", { input })),
	closeTerminalSession: (sessionId: string) => typedError<null, ConfigError>(__TAURI_INVOKE("close_terminal_session", { sessionId })),
	listTerminalColorSchemes: () => typedError<TerminalColorSchemeEntry[], ConfigError>(__TAURI_INVOKE("list_terminal_color_schemes")),
	readTerminalColorScheme: (id: string) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("read_terminal_color_scheme", { id })),
	createTerminalColorScheme: (input: TerminalColorSchemeInput) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("create_terminal_color_scheme", { input })),
	updateTerminalColorScheme: (input: TerminalColorSchemeInput) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("update_terminal_color_scheme", { input })),
	deleteTerminalColorScheme: (id: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_terminal_color_scheme", { id })),
	exportTerminalColorScheme: (id: string) => typedError<string, ConfigError>(__TAURI_INVOKE("export_terminal_color_scheme", { id })),
	exportTerminalColorSchemeToPath: (input: TerminalColorSchemeExportInput) => typedError<string, ConfigError>(__TAURI_INVOKE("export_terminal_color_scheme_to_path", { input })),
	listFiles: (input: FileListInput) => typedError<FileListResult, ConfigError>(__TAURI_INVOKE("list_files", { input })),
	searchFiles: (input: FileSearchInput) => typedError<FileSearchResult, ConfigError>(__TAURI_INVOKE("search_files", { input })),
	createDirectory: (input: FileCreateDirectoryInput) => typedError<null, ConfigError>(__TAURI_INVOKE("create_directory", { input })),
	renameFile: (input: FileRenameInput) => typedError<null, ConfigError>(__TAURI_INVOKE("rename_file", { input })),
	chmodFile: (input: FileChmodInput) => typedError<null, ConfigError>(__TAURI_INVOKE("chmod_file", { input })),
	deleteFile: (input: FilePathInput) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_file", { input })),
	remoteTrashInfo: (input: FileTrashInfoInput) => typedError<FileTrashInfo, ConfigError>(__TAURI_INVOKE("remote_trash_info", { input })),
	remoteSearchHelperInfo: (input: RemoteSearchHelperInput) => typedError<RemoteSearchHelperInfo, ConfigError>(__TAURI_INVOKE("remote_search_helper_info", { input })),
	trashFile: (input: FilePathInput) => typedError<null, ConfigError>(__TAURI_INVOKE("trash_file", { input })),
	previewFile: (input: FilePreviewInput) => typedError<FilePreviewResult, ConfigError>(__TAURI_INVOKE("preview_file", { input })),
	getTransferQueueSnapshot: () => typedError<TransferQueueSnapshot, ConfigError>(__TAURI_INVOKE("get_transfer_queue_snapshot")),
	createTransferTask: (input: TransferCreateInput) => typedError<TransferQueueSnapshot, ConfigError>(__TAURI_INVOKE("create_transfer_task", { input })),
	cancelTransferTask: (input: TransferTaskInput) => typedError<TransferQueueSnapshot, ConfigError>(__TAURI_INVOKE("cancel_transfer_task", { input })),
	retryTransferTask: (input: TransferTaskInput) => typedError<TransferQueueSnapshot, ConfigError>(__TAURI_INVOKE("retry_transfer_task", { input })),
	getPortForwardSnapshot: (hostId: string) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("get_port_forward_snapshot", { hostId })),
	createOrUpdatePortForwardRule: (input: PortForwardRuleInput_Deserialize) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("create_or_update_port_forward_rule", { input })),
	updatePortForwardDraft: (input: PortForwardDraftInput) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("update_port_forward_draft", { input })),
	clearPortForwardDraft: (hostId: string) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("clear_port_forward_draft", { hostId })),
	checkPortForwardNonLoopbackRisk: (input: PortForwardNonLoopbackRiskInput_Deserialize) => typedError<PortForwardNonLoopbackRisk, ConfigError>(__TAURI_INVOKE("check_port_forward_non_loopback_risk", { input })),
	startPortForwardRule: (input: PortForwardRuleIdInput) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("start_port_forward_rule", { input })),
	stopPortForwardRule: (input: PortForwardRuleIdInput) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("stop_port_forward_rule", { input })),
	deletePortForwardRule: (input: PortForwardRuleIdInput) => typedError<PortForwardSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("delete_port_forward_rule", { input })),
	submitPortForwardSshVerification: (input: PortForwardSshVerificationSubmitInput) => typedError<null, ConfigError>(__TAURI_INVOKE("submit_port_forward_ssh_verification", { input })),
	getWorkspaceLayoutSnapshot: () => typedError<WorkspaceLayoutSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("get_workspace_layout_snapshot")),
	workspaceDispatch: (input: WorkspaceDispatchInput) => typedError<WorkspaceLayoutSnapshot_Serialize, ConfigError>(__TAURI_INVOKE("workspace_dispatch", { input })),
	submitWorkspaceSshVerification: (input: WorkspaceSshVerificationSubmitInput) => typedError<null, ConfigError>(__TAURI_INVOKE("submit_workspace_ssh_verification", { input })),
	listProfiles: () => typedError<ProfileEntry[], ConfigError>(__TAURI_INVOKE("list_profiles")),
	readProfile: (name: string) => typedError<ProfileConfigDocument, ConfigError>(__TAURI_INVOKE("read_profile", { name })),
	createProfile: (input: ProfileDocumentInput) => typedError<ProfileEntry, ConfigError>(__TAURI_INVOKE("create_profile", { input })),
	updateProfile: (input: ProfileDocumentInput) => typedError<ProfileEntry, ConfigError>(__TAURI_INVOKE("update_profile", { input })),
	deleteProfile: (name: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_profile", { name })),
	setActiveProfile: (name: string) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_active_profile", { name })),
	readMainConfig: () => typedError<MainConfigDocument, ConfigError>(__TAURI_INVOKE("read_main_config")),
	updateMainConfig: (document: MainConfigDocument) => typedError<MainConfigDocument, ConfigError>(__TAURI_INVOKE("update_main_config", { document })),
	readConnectionHost: (id: string) => typedError<ConnectionHostEntry_Serialize, ConfigError>(__TAURI_INVOKE("read_connection_host", { id })),
	listConnectionHosts: () => typedError<ConnectionHostEntry_Serialize[], ConfigError>(__TAURI_INVOKE("list_connection_hosts")),
	createConnectionHost: (input: ConnectionHostDocumentInput_Deserialize) => typedError<ConnectionHostEntry_Serialize, ConfigError>(__TAURI_INVOKE("create_connection_host", { input })),
	updateConnectionHost: (input: ConnectionHostDocumentInput_Deserialize) => typedError<ConnectionHostEntry_Serialize, ConfigError>(__TAURI_INVOKE("update_connection_host", { input })),
	deleteConnectionHost: (id: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_connection_host", { id })),
	repairConnectionHostId: (id: string) => typedError<ConnectionHostEntry_Serialize, ConfigError>(__TAURI_INVOKE("repair_connection_host_id", { id })),
	listSshKnownHosts: () => typedError<string[], ConfigError>(__TAURI_INVOKE("list_ssh_known_hosts")),
	setHostDirsCommand: (input: HostDirsInput) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_host_dirs_command", { input })),
	setOpensshConfigFilesCommand: (input: HostDirsInput) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_openssh_config_files_command", { input })),
	setDefaultHostCommand: (hostId: string) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_default_host_command", { hostId })),
	removeConfigKey: (input: ConfigKeyPathInput) => typedError<null, ConfigError>(__TAURI_INVOKE("remove_config_key", { input })),
	showTabBarContextMenu: (input: TabBarContextMenuInput) => typedError<null, ConfigError>(__TAURI_INVOKE("show_tab_bar_context_menu", { input })),
	showAppMenu: (input: AppMenuPopupInput) => typedError<null, ConfigError>(__TAURI_INVOKE("show_app_menu", { input })),
	openSettingsWindow: (mode: string) => typedError<null, ConfigError>(__TAURI_INVOKE("open_settings_window", { mode })),
	openHostManagerWindow: () => typedError<null, ConfigError>(__TAURI_INVOKE("open_host_manager_window")),
	openProfileNewDialog: () => typedError<null, ConfigError>(__TAURI_INVOKE("open_profile_new_dialog")),
	openMainWindow: (route: string | null) => typedError<null, ConfigError>(__TAURI_INVOKE("open_main_window", { route })),
	openWorkspaceFloatingWindow: (floatingWindowId: string) => typedError<null, ConfigError>(__TAURI_INVOKE("open_workspace_floating_window", { floatingWindowId })),
	refreshAppMenu: () => typedError<null, ConfigError>(__TAURI_INVOKE("refresh_app_menu")),
	updateTerminalMenuState: (input: TerminalMenuStateInput) => typedError<null, ConfigError>(__TAURI_INVOKE("update_terminal_menu_state", { input })),
	watchConfigCommand: () => typedError<null, ConfigError>(__TAURI_INVOKE("watch_config_command")),
};

/* Types */
export type AppConfigSnapshot = AppConfigSnapshot_Serialize | AppConfigSnapshot_Deserialize;

export type AppConfigSnapshot_Deserialize = {
	root: ConfigRootInfo,
	main_config: MainConfigDocument,
	profile_config: ProfileConfigDocument,
	effective_config: EffectiveConfigDocument,
	profiles: ProfileEntry[],
	hosts: ConnectionHostEntry_Deserialize[],
};

export type AppConfigSnapshot_Serialize = {
	root: ConfigRootInfo,
	main_config: MainConfigDocument,
	profile_config: ProfileConfigDocument,
	effective_config: EffectiveConfigDocument,
	profiles: ProfileEntry[],
	hosts: ConnectionHostEntry_Serialize[],
};

export type AppMenuPopupInput = {
	root: AppMenuRoot,
	window_label: string,
	x: number | null,
	y: number | null,
};

export type AppMenuRoot = "file" | "edit" | "view" | "window";

export type AttachDetachedTerminalSessionInput = {
	workspace_id: string,
	tool_tab_id: string,
	detached_session_id: string,
	window_label: string,
};

export type ConfigDocumentTarget = "main" | "profile";

export type ConfigError = { kind: "Io"; message: {
	message: string,
} } | { kind: "Parse"; message: {
	message: string,
} } | { kind: "Missing"; message: {
	message: string,
} } | { kind: "Invalid"; message: {
	message: string,
} } | { kind: "Terminal"; message: {
	message: string,
} } | { kind: "SshWorkspaceChallenge"; message: {
	challenge: SshWorkspaceChallenge,
	message: string,
} };

export type ConfigKeyPathInput = {
	target: ConfigDocumentTarget,
	profile: string | null,
	path: string[],
};

export type ConfigRootInfo = {
	root_dir: string,
	active_profile: string,
	main_config_path: string,
	profile_config_path: string,
	state_path: string,
	host_dirs: string[],
	openssh_config_files: string[],
	default_host: string,
};

export type ConfigTable = {
	values: { [key in string]: ConfigValue },
};

export type ConfigValue = { kind: "String"; value: string } | { kind: "Integer"; value: string } | { kind: "Float"; value: number | null } | { kind: "Boolean"; value: boolean } | { kind: "Datetime"; value: string } | { kind: "Array"; value: ConfigValue[] } | { kind: "Table"; value: { [key in string]: ConfigValue } };

export type ConnectionDiagnosticSeverity = "warning" | "error";

export type ConnectionHostDiagnostic = {
	severity: ConnectionDiagnosticSeverity,
	code: string,
	message: string,
};

export type ConnectionHostDocument = ConnectionHostDocument_Serialize | ConnectionHostDocument_Deserialize;

export type ConnectionHostDocumentInput = ConnectionHostDocumentInput_Serialize | ConnectionHostDocumentInput_Deserialize;

export type ConnectionHostDocumentInput_Deserialize = {
	id: string | null,
	directory: string | null,
	folder: string | null,
	document: ConnectionHostDocument_Deserialize,
};

export type ConnectionHostDocumentInput_Serialize = {
	id: string | null,
	directory: string | null,
	folder: string | null,
	document: ConnectionHostDocument_Serialize,
};

export type ConnectionHostDocument_Deserialize = {
	version: number,
	id: string,
	name: string,
	folder: string | null,
	icon: ConnectionHostIcon | null,
	files: HostFilesConfig | null,
	resources: HostResourceConfig | null,
	port_forwards?: PortForwardRule_Deserialize[],
	terminal: HostTerminalConfig | null,
	protocol: ConnectionProtocol,
	local: LocalConnectionConfig | null,
	ssh: SshConnectionConfig | null,
	telnet: TelnetConnectionConfig | null,
};

export type ConnectionHostDocument_Serialize = {
	version: number,
	id: string,
	name: string,
	folder: string | null,
	icon: ConnectionHostIcon | null,
	files: HostFilesConfig | null,
	resources: HostResourceConfig | null,
	port_forwards?: PortForwardRule_Serialize[],
	terminal: HostTerminalConfig | null,
	protocol: ConnectionProtocol,
	local: LocalConnectionConfig | null,
	ssh: SshConnectionConfig | null,
	telnet: TelnetConnectionConfig | null,
};

export type ConnectionHostEntry = ConnectionHostEntry_Serialize | ConnectionHostEntry_Deserialize;

export type ConnectionHostEntry_Deserialize = {
	id: string,
	path: string | null,
	source: ConnectionHostSource,
	read_only: boolean,
	document: ConnectionHostDocument_Deserialize,
	diagnostics: ConnectionHostDiagnostic[],
};

export type ConnectionHostEntry_Serialize = {
	id: string,
	path: string | null,
	source: ConnectionHostSource,
	read_only: boolean,
	document: ConnectionHostDocument_Serialize,
	diagnostics: ConnectionHostDiagnostic[],
};

export type ConnectionHostIcon = { type: "catalog"; name: string } | { type: "image"; mime: string; data_base64: string } | { type: "svg"; svg: string };

export type ConnectionHostSource = "virtual" | "user" | "open_ssh_config";

export type ConnectionProtocol = "local" | "ssh" | "telnet";

export type CreateHostTerminalSessionInput = {
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
	resolved_theme: TerminalColorSchemeVariant | null,
	cwd: string | null,
	workspace_id: string,
	tool_tab_id: string,
	window_label: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type DeleteDetachedTerminalSessionInput = {
	workspace_id: string,
	tool_tab_id: string,
	detached_session_id: string,
};

export type DetachedTerminalSessionsInput = {
	workspace_id: string,
	tool_tab_id: string,
};

export type EffectiveConfigDocument = {
	root: ConfigTable,
};

export type ExistingTerminalSessionInput = {
	session_id: string,
};

export type FileChmodInput = {
	workspace_id: string,
	tool_tab_id: string,
	path: string,
	mode: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FileCreateDirectoryInput = {
	workspace_id: string,
	tool_tab_id: string,
	parent_path: string,
	name: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FileEntry = {
	name: string,
	path: string,
	kind: FileEntryKind,
	size: string | null,
	modified_unix_ms: string | null,
	permissions: string | null,
	owner: string | null,
	group: string | null,
	symlink_target: string | null,
};

export type FileEntryKind = "file" | "directory" | "symlink" | "other";

export type FileListInput = {
	workspace_id: string,
	tool_tab_id: string,
	path: string | null,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FileListResult = {
	provider: FileProviderInfo,
	entries: FileEntry[],
};

export type FilePathInput = {
	workspace_id: string,
	tool_tab_id: string,
	path: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FilePreviewContent = { kind: "text"; text: string } | { kind: "image"; mime: string; data_base64: string } | { kind: "unsupported"; reason: string } | { kind: "too_large"; limit_bytes: number };

export type FilePreviewInput = {
	workspace_id: string,
	tool_tab_id: string,
	path: string,
	text_limit_bytes: number,
	image_limit_bytes: number,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FilePreviewResult = {
	path: string,
	name: string,
	entry_kind: FileEntryKind,
	size: string | null,
	modified_unix_ms: string | null,
	permissions: string | null,
	content: FilePreviewContent,
};

export type FileProviderCapabilities = {
	can_read: boolean,
	can_write: boolean,
	can_rename: boolean,
	can_delete: boolean,
	can_trash: boolean,
	can_chmod: boolean,
	can_symlink: boolean,
	can_watch: boolean,
	can_search_by_name: boolean,
	can_search_content: boolean,
	can_upload_helper: boolean,
	supports_server_side_copy: boolean,
	supports_atomic_rename: boolean,
	supports_metadata_owner_group: boolean,
};

export type FileProviderInfo = {
	kind: FileProviderKind,
	host_id: string,
	root_path: string,
	current_path: string,
	capabilities: FileProviderCapabilities,
};

export type FileProviderKind = "local" | "sftp";

export type FileRenameInput = {
	workspace_id: string,
	tool_tab_id: string,
	source_path: string,
	destination_path: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FileSearchInput = {
	workspace_id: string,
	tool_tab_id: string,
	root_path: string,
	query: string,
	mode: FileSearchMode,
	include_hidden: boolean,
	ignore_ignore_files: boolean,
	follow_symlinks: boolean,
	max_results: number,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type FileSearchMatch = {
	path: string,
	name: string,
	kind: FileEntryKind,
	line_number: number | null,
	line_text: string | null,
	ranges: FileSearchMatchRange[],
};

export type FileSearchMatchRange = {
	start: number,
	end: number,
};

export type FileSearchMode = "name" | "content";

export type FileSearchResult = {
	provider_label: string,
	root_path: string,
	query: string,
	matches: FileSearchMatch[],
	diagnostics: string[],
	truncated: boolean,
};

export type FileTrashInfo = {
	available: boolean,
	home_path: string,
	files_path: string | null,
	info_path: string | null,
	reason: string | null,
};

export type FileTrashInfoInput = {
	workspace_id: string,
	tool_tab_id: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type HostDirsInput = {
	dirs: string[],
};

export type HostFilesConfig = {
	default_path: string | null,
};

export type HostResourceConfig = {
	target_os: RemoteResourceTargetOs | null,
	target_arch: RemoteResourceTargetArch | null,
	remote_provider: ResourceRemoteProviderMode | null,
};

export type HostTerminalConfig = {
	agent_mode: TerminalAgentMode | null,
};

export type LocalConnectionConfig = {
	command: string | null,
	args: string[],
	cwd: string | null,
	env: { [key in string]: string },
};

export type LocalResourceMetricKind = "cpu" | "memory" | "swap" | "gpu" | "disk";

export type MainConfigDocument = {
	root: ConfigTable,
};

export type OpenDetachedTerminalSessionHistoryInput = {
	workspace_id: string,
	tool_tab_id: string,
	detached_session_id: string,
	window_label: string,
};

export type PortForwardDirection = "local_to_remote" | "remote_to_local";

export type PortForwardDraft = {
	name: string,
	direction: PortForwardDirection,
	local_address: string,
	local_port: string,
	remote_address: string,
	remote_port: string,
	persistence: PortForwardPersistence,
	connect_on_host_open: boolean,
};

export type PortForwardDraftInput = {
	host_id: string,
	draft: PortForwardDraft,
};

export type PortForwardEvent = {
	sequence: string,
	occurred_at_unix_ms: string,
	level: PortForwardEventLevel,
	message: string,
};

export type PortForwardEventLevel = "debug" | "info" | "warn" | "error";

export type PortForwardNonLoopbackConfirmation = {
	semantic_key: PortForwardSemanticKey,
	confirmed_at_unix_ms: string,
};

export type PortForwardNonLoopbackRisk = {
	requires_confirmation: boolean,
	listen_address: string,
	reasons: string[],
};

export type PortForwardNonLoopbackRiskInput = PortForwardNonLoopbackRiskInput_Serialize | PortForwardNonLoopbackRiskInput_Deserialize;

export type PortForwardNonLoopbackRiskInput_Deserialize = {
	rule: PortForwardRule_Deserialize,
};

export type PortForwardNonLoopbackRiskInput_Serialize = {
	rule: PortForwardRule_Serialize,
};

export type PortForwardPersistence = "just_this_time" | "saved";

export type PortForwardRule = PortForwardRule_Serialize | PortForwardRule_Deserialize;

export type PortForwardRuleIdInput = {
	host_id: string,
	rule_id: string,
};

export type PortForwardRuleInput = PortForwardRuleInput_Serialize | PortForwardRuleInput_Deserialize;

export type PortForwardRuleInput_Deserialize = {
	host_id: string,
	rule: PortForwardRule_Deserialize,
	persistence: PortForwardPersistence,
};

export type PortForwardRuleInput_Serialize = {
	host_id: string,
	rule: PortForwardRule_Serialize,
	persistence: PortForwardPersistence,
};

export type PortForwardRuleSnapshot = PortForwardRuleSnapshot_Serialize | PortForwardRuleSnapshot_Deserialize;

export type PortForwardRuleSnapshot_Deserialize = {
	rule: PortForwardRule_Deserialize,
	runtime: PortForwardRuntimeRule,
};

export type PortForwardRuleSnapshot_Serialize = {
	rule: PortForwardRule_Serialize,
	runtime: PortForwardRuntimeRule,
};

export type PortForwardRuleStatus = "stopped" | "starting" | "running" | "reconnecting" | "failed" | "needs_confirmation";

export type PortForwardRule_Deserialize = {
	id: string,
	name: string,
	direction: PortForwardDirection,
	local_address: string,
	local_port: number,
	remote_address: string,
	remote_port: number,
	connect_on_host_open?: boolean,
	non_loopback_confirmations?: PortForwardNonLoopbackConfirmation[],
};

export type PortForwardRule_Serialize = {
	id: string,
	name: string,
	direction: PortForwardDirection,
	local_address: string,
	local_port: number,
	remote_address: string,
	remote_port: number,
	connect_on_host_open: boolean,
	non_loopback_confirmations?: PortForwardNonLoopbackConfirmation[],
};

export type PortForwardRuntimeRule = {
	rule_id: string,
	persistence: PortForwardPersistence,
	status: PortForwardRuleStatus,
	intended_running: boolean,
	active_connections: number,
	effective_local_port: number | null,
	effective_remote_port: number | null,
	warning: string | null,
	error: string | null,
	events: PortForwardEvent[],
};

export type PortForwardSemanticKey = {
	direction: PortForwardDirection,
	local_address: string,
	local_port: number,
	remote_address: string,
	remote_port: number,
};

export type PortForwardSnapshot = PortForwardSnapshot_Serialize | PortForwardSnapshot_Deserialize;

export type PortForwardSnapshot_Deserialize = {
	host_id: string,
	supported: boolean,
	unsupported_reason: string | null,
	rules: PortForwardRuleSnapshot_Deserialize[],
	draft: PortForwardDraft | null,
};

export type PortForwardSnapshot_Serialize = {
	host_id: string,
	supported: boolean,
	unsupported_reason: string | null,
	rules: PortForwardRuleSnapshot_Serialize[],
	draft: PortForwardDraft | null,
};

export type PortForwardSshVerificationRequiredEvent = {
	host_id: string,
	verification_id: string,
	challenge: SshHostScopedChallenge,
};

export type PortForwardSshVerificationSubmitInput = {
	host_id: string,
	verification_id: string,
	response: WorkspaceSshVerificationResponse,
};

export type ProfileConfigDocument = {
	root: ConfigTable,
};

export type ProfileDocumentInput = {
	name: string,
	document: ProfileConfigDocument,
};

export type ProfileEntry = {
	name: string,
	path: string,
};

export type RemoteResourceTargetArch = "x86_64" | "aarch64" | "armv7" | "i686";

export type RemoteResourceTargetOs = "linux" | "macos" | "windows";

export type RemoteSearchHelperInfo = {
	available: boolean,
	provider_label: string,
	reason: string | null,
};

export type RemoteSearchHelperInput = {
	workspace_id: string,
	tool_tab_id: string,
	accept_new_host_key: boolean,
	update_changed_host_key: boolean,
	credential: SshCredentialInput | null,
	save_credential: boolean,
};

export type ResourceMonitorCollectInput = {
	workspace_id: string,
	tool_tab_id: string,
};

export type ResourceMonitorDiskMount = {
	id: string,
	mount_point: string,
	device_name: string,
	file_system: string,
	used: string,
	total: string,
	available: string,
	percent: number | null,
};

export type ResourceMonitorGpuDevice = {
	id: string,
	label: string,
	compute_percent: number | null,
	compute_unavailable_reason: string | null,
	memory_used: string,
	memory_total: string,
};

export type ResourceMonitorMetric = {
	metric: LocalResourceMetricKind,
	status: string,
	used: string | null,
	total: string | null,
	percent: number | null,
	available: string | null,
	free: string | null,
	reason: string | null,
	cores: (number | null)[],
	gpus: ResourceMonitorGpuDevice[],
	disks: ResourceMonitorDiskMount[],
};

export type ResourceMonitorSnapshot = {
	provider: string,
	collected_at_ms: string,
	metrics: ResourceMonitorMetric[],
};

export type ResourceRefreshInterval = "one_second" | "two_seconds" | "five_seconds" | "ten_seconds";

export type ResourceRemoteProviderMode = "auto" | "agent" | "system_commands";

export type ResourceSettings = {
	default_refresh_interval: ResourceRefreshInterval,
};

export type SshAuthTarget = {
	id: string,
	kind: SshAuthTargetKind,
	label: string,
	username: string,
	hostname: string,
	port: number,
};

export type SshAuthTargetKind = "connection_host" | "proxy_jump";

export type SshConnectionConfig = {
	hostname: string,
	port: number,
	username: string | null,
	identity_file: string | null,
	proxy_jump: string | null,
	forward_agent: boolean,
	server_alive_interval: number | null,
};

export type SshCredentialChallenge = {
	workspace_id: string,
	source_tool_tab_id: string | null,
	auth_target: SshAuthTarget,
	credential_kind: SshCredentialKind,
	identity_file: string | null,
};

export type SshCredentialInput = {
	kind: SshCredentialKind,
	value: string,
};

export type SshCredentialKind = "password" | "key_passphrase";

export type SshHostKeyChallenge = {
	workspace_id: string,
	source_tool_tab_id: string | null,
	auth_target: SshAuthTarget,
	challenge_kind: SshHostKeyChallengeKind,
	target: string,
	algorithm: string,
	fingerprint: string,
};

export type SshHostKeyChallengeKind = "unknown" | "changed";

export type SshHostScopedChallenge = { kind: "credential"; challenge: SshCredentialChallenge } | { kind: "host_key"; challenge: SshHostKeyChallenge };

export type SshWorkspaceChallenge = { kind: "credential"; challenge: SshCredentialChallenge } | { kind: "host_key"; challenge: SshHostKeyChallenge };

export type TabBarContextMenuInput = {
	x: number | null,
	y: number | null,
	window_label: string,
};

export type TabBarOrientation = "horizontal" | "vertical_left" | "vertical_right";

export type TelnetConnectionConfig = {
	hostname: string,
	port: number,
};

export type TerminalAgentMode = "enabled" | "disabled";

export type TerminalAgentSessionInfo = {
	session_id: string,
};

export type TerminalColorScheme = {
	id: string,
	name: string,
	author: string | null,
	variant: TerminalColorSchemeVariant,
	background: string,
	foreground: string,
	cursor: string,
	selection_background: string,
	black: string,
	red: string,
	green: string,
	yellow: string,
	blue: string,
	magenta: string,
	cyan: string,
	white: string,
	bright_black: string,
	bright_red: string,
	bright_green: string,
	bright_yellow: string,
	bright_blue: string,
	bright_magenta: string,
	bright_cyan: string,
	bright_white: string,
};

export type TerminalColorSchemeEntry = {
	id: string,
	source: TerminalColorSchemeSource,
	path: string | null,
	scheme: TerminalColorScheme,
};

export type TerminalColorSchemeExportInput = {
	id: string,
	path: string,
};

export type TerminalColorSchemeInput = {
	id: string | null,
	scheme: TerminalColorScheme,
};

export type TerminalColorSchemeSource = "builtin" | "user" | "legacy";

export type TerminalColorSchemeVariant = "light" | "dark";

export type TerminalCursorStyle = "block" | "underline" | "bar";

export type TerminalDetachInput = {
	session_id: string,
};

export type TerminalDetachedSessionInfo = {
	session_id: string,
	title: string,
	command: string,
	cwd: string | null,
	cols: number,
	rows: number,
	detached: boolean,
	attached_count: number,
};

export type TerminalInput = {
	session_id: string,
	data: string,
};

export type TerminalMenuStateInput = {
	can_edit_text: boolean,
	can_undo_text: boolean,
	can_redo_text: boolean,
	has_active_tab: boolean,
	has_multiple_tabs: boolean,
	has_selection: boolean,
	can_paste: boolean,
	can_paste_selection: boolean,
	can_select_all: boolean,
	can_jump_to_selection: boolean,
	find_visible: boolean,
	has_find_query: boolean,
};

export type TerminalOutputBacklogInput = {
	session_id: string,
};

export type TerminalOutputEvent = {
	session_id: string,
	sequence: string,
	backlog: boolean,
	data: string,
};

export type TerminalPadding = {
	top: number | null,
	right: number | null,
	bottom: number | null,
	left: number | null,
};

export type TerminalRenderer = "dom" | "webgl";

export type TerminalSessionInfo = {
	id: string,
	title: string,
	command: string,
	cwd: string | null,
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
	process_id: number | null,
	transport: TerminalTransportKind,
	transport_state: TerminalTransportState,
	agent: TerminalAgentSessionInfo | null,
};

export type TerminalSessionOwnershipInput = {
	session_ids: string[],
	window_label: string,
};

export type TerminalSettings = {
	command: string | null,
	args: string[],
	cwd: string | null,
	font_family: string,
	font_size: number | null,
	scrollback: number,
	renderer: TerminalRenderer,
	cursor_blink: boolean,
	cursor_style: TerminalCursorStyle,
	theme: TerminalTheme,
	padding: TerminalPadding,
	tab_bar_orientation: TabBarOrientation,
};

export type TerminalSettingsInput = {
	resolved_theme: TerminalColorSchemeVariant | null,
};

export type TerminalSizeInput = {
	session_id: string,
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
};

export type TerminalTheme = {
	background: string,
	foreground: string,
	cursor: string,
	selection_background: string,
	black: string,
	red: string,
	green: string,
	yellow: string,
	blue: string,
	magenta: string,
	cyan: string,
	white: string,
	bright_black: string,
	bright_red: string,
	bright_green: string,
	bright_yellow: string,
	bright_blue: string,
	bright_magenta: string,
	bright_cyan: string,
	bright_white: string,
};

export type TerminalTitleInput = {
	session_id: string,
	title: string,
};

export type TerminalTransportKind = "local" | "ssh" | "telnet" | "agent";

export type TerminalTransportState = "resolving" | "connecting" | "verifying_host_key" | "authenticating" | "waiting_for_workspace_verification" | "connected" | "disconnected" | "failed";

export type TransferCreateInput = {
	source: TransferEndpoint,
	destination: TransferEndpoint,
	initiator_workspace_id: string | null,
	related_workspace_ids: string[],
};

export type TransferEndpoint = {
	kind: TransferEndpointKind,
	provider_kind: FileProviderKind | null,
	host_id: string | null,
	path: string,
};

export type TransferEndpointKind = "local" | "provider";

export type TransferQueueChangedEvent = {
	version: number,
	snapshot: TransferQueueSnapshot,
};

export type TransferQueueSnapshot = {
	version: number,
	tasks: TransferTask[],
};

export type TransferTask = {
	id: string,
	source: TransferEndpoint,
	destination: TransferEndpoint,
	initiator_workspace_id: string | null,
	related_workspace_ids: string[],
	status: TransferTaskStatus,
	bytes_total: string | null,
	bytes_done: string,
	error: string | null,
	created_at_unix_ms: string,
	updated_at_unix_ms: string,
};

export type TransferTaskInput = {
	task_id: string,
};

export type TransferTaskStatus = "queued" | "running" | "failed" | "completed" | "canceled";

export type WorkspaceChangedEvent = WorkspaceChangedEvent_Serialize | WorkspaceChangedEvent_Deserialize;

export type WorkspaceChangedEvent_Deserialize = {
	version: number,
	reason: string,
	snapshot: WorkspaceLayoutSnapshot_Deserialize,
};

export type WorkspaceChangedEvent_Serialize = {
	version: number,
	reason: string,
	snapshot: WorkspaceLayoutSnapshot_Serialize,
};

export type WorkspaceDispatchInput = {
	expected_version: number,
	intent: WorkspaceIntent,
};

export type WorkspaceDockDirection = "row" | "column";

export type WorkspaceDockGroupRole = WorkspaceDockGroupRole_Serialize | WorkspaceDockGroupRole_Deserialize;

export type WorkspaceDockGroupRole_Deserialize = "content" | "side_panel" | "sidebar" | "panel";

export type WorkspaceDockGroupRole_Serialize = "content" | "side_panel";

export type WorkspaceDockLayout = WorkspaceDockLayout_Serialize | WorkspaceDockLayout_Deserialize;

export type WorkspaceDockLayout_Deserialize = ({ kind: "split"; direction: WorkspaceDockDirection; children: WorkspaceDockLayout_Deserialize[]; ratios: (number | null)[] }) & { active_slot_id?: never; collapsed?: never; id?: never; role?: never; slots?: never } | ({ kind: "group"; id: string; role: WorkspaceDockGroupRole_Deserialize; slots: WorkspaceToolSlot[]; active_slot_id: string; collapsed?: boolean }) & { children?: never; direction?: never; ratios?: never };

export type WorkspaceDockLayout_Serialize = ({ kind: "split"; direction: WorkspaceDockDirection; children: WorkspaceDockLayout_Serialize[]; ratios: (number | null)[] }) & { active_slot_id?: never; collapsed?: never; id?: never; role?: never; slots?: never } | ({ kind: "group"; id: string; role: WorkspaceDockGroupRole_Serialize; slots: WorkspaceToolSlot[]; active_slot_id: string; collapsed: boolean }) & { children?: never; direction?: never; ratios?: never };

export type WorkspaceDockSide = "left" | "right" | "up" | "down";

export type WorkspaceFloatingWindowState = WorkspaceFloatingWindowState_Serialize | WorkspaceFloatingWindowState_Deserialize;

export type WorkspaceFloatingWindowState_Deserialize = {
	id: string,
	layout: WorkspaceDockLayout_Deserialize,
};

export type WorkspaceFloatingWindowState_Serialize = {
	id: string,
	layout: WorkspaceDockLayout_Serialize,
};

export type WorkspaceIntent = { kind: "create_workspace"; host_id: string } | { kind: "activate_workspace"; workspace_id: string } | { kind: "rename_workspace"; workspace_id: string; title: string } | { kind: "close_workspace"; workspace_id: string } | { kind: "close_other_workspaces"; workspace_id: string } | { kind: "close_workspaces_to_right"; workspace_id: string } | { kind: "activate_tool_slot"; workspace_id: string; slot_id: string } | { kind: "set_dock_group_collapsed"; workspace_id: string; group_id: string; collapsed: boolean } | { kind: "close_tool_slot"; workspace_id: string; slot_id: string } | { kind: "close_other_tool_slots"; workspace_id: string; slot_id: string } | { kind: "close_tool_slots_to_right"; workspace_id: string; slot_id: string } | { kind: "mirror_tool_tab"; source_tool_tab_id: string; target_workspace_id: string; target_group_id: string } | { kind: "float_tool_slot"; workspace_id: string; slot_id: string } | { kind: "close_floating_window"; floating_window_id: string } | { kind: "move_tool_slot_to_group"; workspace_id: string; slot_id: string; target_group_id: string } | { kind: "move_tool_slot_to_split"; workspace_id: string; slot_id: string; target_slot_id: string; side: WorkspaceDockSide } | { kind: "move_tool_slot_to_workspace_edge"; workspace_id: string; slot_id: string; side: WorkspaceDockSide } | { kind: "split_tool_slot"; workspace_id: string; target_slot_id: string; tool_tab_id: string; side: WorkspaceDockSide } | { kind: "create_terminal_tool_tab"; workspace_id: string; target_group_id: string | null } | { kind: "open_terminal_sessions_tool_tab"; workspace_id: string; target_group_id: string | null } | { kind: "open_resource_monitor_tool_tab"; workspace_id: string; target_group_id: string | null };

export type WorkspaceLayoutSnapshot = WorkspaceLayoutSnapshot_Serialize | WorkspaceLayoutSnapshot_Deserialize;

export type WorkspaceLayoutSnapshot_Deserialize = {
	version: number,
	active_workspace_id: string,
	workspaces: WorkspaceTabState_Deserialize[],
	tool_tabs: WorkspaceToolTab[],
	floating_windows: WorkspaceFloatingWindowState_Deserialize[],
};

export type WorkspaceLayoutSnapshot_Serialize = {
	version: number,
	active_workspace_id: string,
	workspaces: WorkspaceTabState_Serialize[],
	tool_tabs: WorkspaceToolTab[],
	floating_windows: WorkspaceFloatingWindowState_Serialize[],
};

export type WorkspaceSshVerificationRequiredEvent = {
	workspace_id: string,
	verification_id: string,
	challenge: SshWorkspaceChallenge,
};

export type WorkspaceSshVerificationResponse = { kind: "credential"; credential: SshCredentialInput; save_credential: boolean } | { kind: "host_key"; accept_new_host_key: boolean; update_changed_host_key: boolean } | { kind: "cancel" };

export type WorkspaceSshVerificationSubmitInput = {
	workspace_id: string,
	verification_id: string,
	response: WorkspaceSshVerificationResponse,
};

export type WorkspaceTabState = WorkspaceTabState_Serialize | WorkspaceTabState_Deserialize;

export type WorkspaceTabState_Deserialize = {
	id: string,
	host_id: string,
	title: string,
	owned_tool_tab_ids: string[],
	layout: WorkspaceDockLayout_Deserialize,
};

export type WorkspaceTabState_Serialize = {
	id: string,
	host_id: string,
	title: string,
	owned_tool_tab_ids: string[],
	layout: WorkspaceDockLayout_Serialize,
};

export type WorkspaceToolKind = "files" | "terminal" | "terminal_sessions" | "transfers" | "resources" | "ports";

export type WorkspaceToolSlot = { kind: "owned"; id: string; tool_tab_id: string } | { kind: "mirror"; id: string; tool_tab_id: string; owner_workspace_id: string } | { kind: "floating_placeholder"; id: string; tool_tab_id: string; floating_window_id: string } | { kind: "closed_source"; id: string; previous_title: string; owner_workspace_title: string };

export type WorkspaceToolTab = {
	id: string,
	kind: WorkspaceToolKind,
	owner_workspace_id: string,
	host_id: string,
	title: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

