// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getConfigRoot: () => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("get_config_root")),
	getConfigSnapshot: () => typedError<AppConfigSnapshot, ConfigError>(__TAURI_INVOKE("get_config_snapshot")),
	getTerminalSettings: () => typedError<TerminalSettings, ConfigError>(__TAURI_INVOKE("get_terminal_settings")),
	getTerminalSettingsForTheme: (input: TerminalSettingsInput) => typedError<TerminalSettings, ConfigError>(__TAURI_INVOKE("get_terminal_settings_for_theme", { input })),
	createTerminalSession: (input: CreateTerminalSessionInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("create_terminal_session", { input })),
	existingTerminalSessionInfo: (input: ExistingTerminalSessionInput) => typedError<TerminalSessionInfo, ConfigError>(__TAURI_INVOKE("existing_terminal_session_info", { input })),
	transferTerminalSessionsToWindow: (input: TerminalSessionOwnershipInput) => typedError<null, ConfigError>(__TAURI_INVOKE("transfer_terminal_sessions_to_window", { input })),
	takeTerminalOutputBacklog: (input: TerminalOutputBacklogInput) => typedError<{
	session_id: string,
	sequence: string,
	backlog: boolean,
	data: string,
} | null, ConfigError>(__TAURI_INVOKE("take_terminal_output_backlog", { input })),
	writeTerminal: (input: TerminalInput) => typedError<null, ConfigError>(__TAURI_INVOKE("write_terminal", { input })),
	resizeTerminal: (input: TerminalSizeInput) => typedError<null, ConfigError>(__TAURI_INVOKE("resize_terminal", { input })),
	closeTerminalSession: (sessionId: string) => typedError<null, ConfigError>(__TAURI_INVOKE("close_terminal_session", { sessionId })),
	listTerminalColorSchemes: () => typedError<TerminalColorSchemeEntry[], ConfigError>(__TAURI_INVOKE("list_terminal_color_schemes")),
	readTerminalColorScheme: (id: string) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("read_terminal_color_scheme", { id })),
	createTerminalColorScheme: (input: TerminalColorSchemeInput) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("create_terminal_color_scheme", { input })),
	updateTerminalColorScheme: (input: TerminalColorSchemeInput) => typedError<TerminalColorSchemeEntry, ConfigError>(__TAURI_INVOKE("update_terminal_color_scheme", { input })),
	deleteTerminalColorScheme: (id: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_terminal_color_scheme", { id })),
	exportTerminalColorScheme: (id: string) => typedError<string, ConfigError>(__TAURI_INVOKE("export_terminal_color_scheme", { id })),
	exportTerminalColorSchemeToPath: (input: TerminalColorSchemeExportInput) => typedError<string, ConfigError>(__TAURI_INVOKE("export_terminal_color_scheme_to_path", { input })),
	listProfiles: () => typedError<ProfileEntry[], ConfigError>(__TAURI_INVOKE("list_profiles")),
	readProfile: (name: string) => typedError<ProfileConfigDocument, ConfigError>(__TAURI_INVOKE("read_profile", { name })),
	createProfile: (input: ProfileDocumentInput) => typedError<ProfileEntry, ConfigError>(__TAURI_INVOKE("create_profile", { input })),
	updateProfile: (input: ProfileDocumentInput) => typedError<ProfileEntry, ConfigError>(__TAURI_INVOKE("update_profile", { input })),
	deleteProfile: (name: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_profile", { name })),
	setActiveProfile: (name: string) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_active_profile", { name })),
	readMainConfig: () => typedError<MainConfigDocument, ConfigError>(__TAURI_INVOKE("read_main_config")),
	updateMainConfig: (document: MainConfigDocument) => typedError<MainConfigDocument, ConfigError>(__TAURI_INVOKE("update_main_config", { document })),
	readHost: (id: string) => typedError<HostEntry, ConfigError>(__TAURI_INVOKE("read_host", { id })),
	listHosts: () => typedError<HostEntry[], ConfigError>(__TAURI_INVOKE("list_hosts")),
	createHost: (document: HostConfigDocument) => typedError<HostEntry, ConfigError>(__TAURI_INVOKE("create_host", { document })),
	updateHost: (input: HostDocumentInput) => typedError<HostEntry, ConfigError>(__TAURI_INVOKE("update_host", { input })),
	deleteHost: (id: string) => typedError<null, ConfigError>(__TAURI_INVOKE("delete_host", { id })),
	setHostDirsCommand: (input: HostDirsInput) => typedError<ConfigRootInfo, ConfigError>(__TAURI_INVOKE("set_host_dirs_command", { input })),
	removeConfigKey: (input: ConfigKeyPathInput) => typedError<null, ConfigError>(__TAURI_INVOKE("remove_config_key", { input })),
	showTabBarContextMenu: (input: TabBarContextMenuInput) => typedError<null, ConfigError>(__TAURI_INVOKE("show_tab_bar_context_menu", { input })),
	showPaneContextMenu: (input: PaneContextMenuInput) => typedError<null, ConfigError>(__TAURI_INVOKE("show_pane_context_menu", { input })),
	openMainWindow: (route: string | null) => typedError<null, ConfigError>(__TAURI_INVOKE("open_main_window", { route })),
	refreshAppMenu: () => typedError<null, ConfigError>(__TAURI_INVOKE("refresh_app_menu")),
	updateTerminalMenuState: (input: TerminalMenuStateInput) => typedError<null, ConfigError>(__TAURI_INVOKE("update_terminal_menu_state", { input })),
	watchConfigCommand: () => typedError<null, ConfigError>(__TAURI_INVOKE("watch_config_command")),
};

/* Types */
export type AppConfigSnapshot = {
	root: ConfigRootInfo,
	main_config: MainConfigDocument,
	profile_config: ProfileConfigDocument,
	effective_config: EffectiveConfigDocument,
	profiles: ProfileEntry[],
	hosts: HostEntry[],
};

export type ConfigDocumentTarget = "main" | "profile";

export type ConfigError = { kind: "Io"; message: {
	message: string,
} } | { kind: "Parse"; message: {
	message: string,
} } | { kind: "Missing"; message: {
	message: string,
} } | { kind: "Invalid"; message: {
	message: string,
} } | { kind: "Terminal"; message: {
	message: string,
} };

export type ConfigKeyPathInput = {
	target: ConfigDocumentTarget,
	profile: string | null,
	path: string[],
};

export type ConfigRootInfo = {
	root_dir: string,
	active_profile: string,
	main_config_path: string,
	profile_config_path: string,
	state_path: string,
	host_dirs: string[],
};

export type ConfigTable = {
	values: { [key in string]: ConfigValue },
};

export type ConfigValue = { kind: "String"; value: string } | { kind: "Integer"; value: string } | { kind: "Float"; value: number | null } | { kind: "Boolean"; value: boolean } | { kind: "Datetime"; value: string } | { kind: "Array"; value: ConfigValue[] } | { kind: "Table"; value: { [key in string]: ConfigValue } };

export type CreateTerminalSessionInput = {
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
	resolved_theme: TerminalColorSchemeVariant | null,
	cwd: string | null,
	window_label: string,
};

export type EffectiveConfigDocument = {
	root: ConfigTable,
};

export type ExistingTerminalSessionInput = {
	session_id: string,
};

export type HostConfigDocument = {
	root: ConfigTable,
};

export type HostDirsInput = {
	dirs: string[],
};

export type HostDocumentInput = {
	id: string | null,
	document: HostConfigDocument,
};

export type HostEntry = {
	id: string,
	path: string,
	document: HostConfigDocument,
};

export type MainConfigDocument = {
	root: ConfigTable,
};

export type PaneContextMenuInput = {
	x: number | null,
	y: number | null,
	pane_id: string,
	window_label: string,
	has_selection: boolean,
	read_only: boolean,
};

export type ProfileConfigDocument = {
	root: ConfigTable,
};

export type ProfileDocumentInput = {
	name: string,
	document: ProfileConfigDocument,
};

export type ProfileEntry = {
	name: string,
	path: string,
};

export type TabBarContextMenuInput = {
	x: number | null,
	y: number | null,
	window_label: string,
};

export type TabBarOrientation = "horizontal" | "vertical_left" | "vertical_right";

export type TerminalColorScheme = {
	id: string,
	name: string,
	author: string | null,
	variant: TerminalColorSchemeVariant,
	background: string,
	foreground: string,
	cursor: string,
	selection_background: string,
	black: string,
	red: string,
	green: string,
	yellow: string,
	blue: string,
	magenta: string,
	cyan: string,
	white: string,
	bright_black: string,
	bright_red: string,
	bright_green: string,
	bright_yellow: string,
	bright_blue: string,
	bright_magenta: string,
	bright_cyan: string,
	bright_white: string,
};

export type TerminalColorSchemeEntry = {
	id: string,
	source: TerminalColorSchemeSource,
	path: string | null,
	scheme: TerminalColorScheme,
};

export type TerminalColorSchemeExportInput = {
	id: string,
	path: string,
};

export type TerminalColorSchemeInput = {
	id: string | null,
	scheme: TerminalColorScheme,
};

export type TerminalColorSchemeSource = "builtin" | "user" | "legacy";

export type TerminalColorSchemeVariant = "light" | "dark";

export type TerminalCursorStyle = "block" | "underline" | "bar";

export type TerminalInput = {
	session_id: string,
	data: string,
};

export type TerminalMenuCommand = "new_window" | "new_tab" | "split_right" | "split_left" | "split_down" | "split_up" | "close" | "close_tab" | "close_window" | "undo" | "redo" | "copy" | "paste" | "paste_selection" | "select_all" | "find" | "find_next" | "find_previous" | "hide_find_bar" | "use_selection_for_find" | "jump_to_selection" | "reset_font_size" | "increase_font_size" | "decrease_font_size" | "change_tab_title" | "toggle_read_only" | "minimize" | "zoom" | "fill" | "center" | "move_resize_left" | "move_resize_right" | "move_resize_top" | "move_resize_bottom" | "move_resize_top_left" | "move_resize_top_right" | "move_resize_bottom_left" | "move_resize_bottom_right" | "toggle_full_screen" | "show_previous_tab" | "show_next_tab" | "move_tab_to_new_window" | "zoom_split" | "select_previous_split" | "select_next_split" | "select_split_left" | "select_split_right" | "select_split_up" | "select_split_down" | "resize_split_left" | "resize_split_right" | "resize_split_up" | "resize_split_down" | "bring_all_to_front";

export type TerminalMenuEvent = {
	command: TerminalMenuCommand,
};

export type TerminalMenuStateInput = {
	can_edit_text: boolean,
	can_undo_text: boolean,
	can_redo_text: boolean,
	has_active_tab: boolean,
	has_active_pane: boolean,
	has_multiple_tabs: boolean,
	has_multiple_panes: boolean,
	has_selection: boolean,
	can_paste: boolean,
	can_paste_selection: boolean,
	can_select_all: boolean,
	can_jump_to_selection: boolean,
	find_visible: boolean,
	has_find_query: boolean,
};

export type TerminalOutputBacklogInput = {
	session_id: string,
};

export type TerminalOutputEvent = {
	session_id: string,
	sequence: string,
	backlog: boolean,
	data: string,
};

export type TerminalPadding = {
	top: number | null,
	right: number | null,
	bottom: number | null,
	left: number | null,
};

export type TerminalRenderer = "dom" | "webgl";

export type TerminalSessionInfo = {
	id: string,
	title: string,
	command: string,
	cwd: string | null,
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
	process_id: number | null,
};

export type TerminalSessionOwnershipInput = {
	session_ids: string[],
	window_label: string,
};

export type TerminalSettings = {
	command: string | null,
	args: string[],
	cwd: string | null,
	font_family: string,
	font_size: number | null,
	scrollback: number,
	renderer: TerminalRenderer,
	cursor_blink: boolean,
	cursor_style: TerminalCursorStyle,
	theme: TerminalTheme,
	padding: TerminalPadding,
	tab_bar_orientation: TabBarOrientation,
};

export type TerminalSettingsInput = {
	resolved_theme: TerminalColorSchemeVariant | null,
};

export type TerminalSizeInput = {
	session_id: string,
	cols: number,
	rows: number,
	pixel_width: number,
	pixel_height: number,
};

export type TerminalTheme = {
	background: string,
	foreground: string,
	cursor: string,
	selection_background: string,
	black: string,
	red: string,
	green: string,
	yellow: string,
	blue: string,
	magenta: string,
	cyan: string,
	white: string,
	bright_black: string,
	bright_red: string,
	bright_green: string,
	bright_yellow: string,
	bright_blue: string,
	bright_magenta: string,
	bright_cyan: string,
	bright_white: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

